#!/usr/bin/env Rscript
# Check the local R/Ubuntu environment and write a session-info file.

required <- c("data.table", "future", "future.apply", "parallelly", "ggplot2")
optional <- c("RhpcBLASctl", "renv")

cat("BS2 reproducibility environment check\n")
cat(strrep("=", 72), "\n", sep = "")
cat("R version: ", R.version.string, "\n", sep = "")
cat("Platform : ", R.version$platform, "\n", sep = "")
cat("OS       : ", Sys.info()[["sysname"]], " ", Sys.info()[["release"]], "\n", sep = "")
cat("Working directory: ", normalizePath(getwd()), "\n", sep = "")

if (.Platform$OS.type == "unix") {
  nproc <- suppressWarnings(as.integer(system("nproc", intern = TRUE)))
  if (length(nproc) == 1L && is.finite(nproc)) cat("nproc    : ", nproc, "\n", sep = "")
}

cat("\nPackages\n")
cat(strrep("-", 72), "\n", sep = "")
missing <- character(0)
for (pkg in required) {
  ok <- requireNamespace(pkg, quietly = TRUE)
  if (!ok) missing <- c(missing, pkg)
  cat(sprintf("%-15s %s\n", pkg, if (ok) as.character(utils::packageVersion(pkg)) else "MISSING"))
}
for (pkg in optional) {
  ok <- requireNamespace(pkg, quietly = TRUE)
  cat(sprintf("%-15s %s %s\n", pkg, if (ok) as.character(utils::packageVersion(pkg)) else "not installed", "(optional)"))
}

cat("\nParallel support\n")
cat(strrep("-", 72), "\n", sep = "")
if (requireNamespace("parallelly", quietly = TRUE)) {
  cat("availableCores(): ", parallelly::availableCores(), "\n", sep = "")
  cat("supportsMulticore(): ", parallelly::supportsMulticore(), "\n", sep = "")
}

cat("\nRepository files\n")
cat(strrep("-", 72), "\n", sep = "")
needed <- c(
  "R/bs2_core.R",
  "R/sim_designs.R",
  "R/sim_parallel_utils.R",
  "data/bmd.csv",
  "scripts/01_estimation_parallel.R",
  "scripts/02_tests_parallel.R",
  "scripts/03_bootstrap_lr_parallel.R",
  "scripts/04_aggregate_results.R",
  "scripts/05_power_parallel.R",
  "scripts/06_gof_influence_parallel.R",
  "scripts/07_make_figures_publication.R",
  "scripts/08_bmd_analysis.R"
)
for (f in needed) cat(sprintf("%-45s %s\n", f, if (file.exists(f)) "OK" else "MISSING"))

if (length(missing) > 0L) {
  cat("\nMissing required packages: ", paste(missing, collapse = ", "), "\n", sep = "")
  cat("Run: Rscript scripts/00_install.R\n")
}

dir.create("results", showWarnings = FALSE, recursive = TRUE)
sink("results/sessionInfo.txt")
cat("Generated by scripts/00_check_environment.R at ", as.character(Sys.time()), "\n\n", sep = "")
print(sessionInfo())
sink()
cat("\nWrote results/sessionInfo.txt\n")

if (length(missing) > 0L) quit(status = 1L)
